{'cluster_id': 'c75bb10b-0708-498e-b403-20637d43e8b6',
 'control_plane_nodes': {'groups': {'13c9f641-8a9a-3515-8f1b-b0546cd7ec47': {'group_status': 'STABLE',
                                                                             'group_type': 'CORFU_NONCONFIG',
                                                                             'members': [{'member_fqdn': 'nsx-t-a.cpod-go.az-fkd.cloud-garage.net',
                                                                                          'member_ip': '172.17.23.123',
                                                                                          'member_status': 'UNKNOWN',
                                                                                          'member_uuid': '4c1f0642-9739-7919-c5b7-ea9b971d9eb3'},
                                                                                         {'member_fqdn': 'nsx-t-b.cpod-go.az-fkd.cloud-garage.net',
                                                                                          'member_ip': '172.17.23.124',
                                                                                          'member_status': 'UP',
                                                                                          'member_uuid': 'b0fb0642-03b2-91bd-ac6c-4644fe2b8fa3'},
                                                                                         {'member_fqdn': 'nsx-t-c.cpod-go.az-fkd.cloud-garage.net',
                                                                                          'member_ip': '172.17.23.125',
                                                                                          'member_status': 'UP',
                                                                                          'member_uuid': '9dd40642-7e06-7918-dd54-a828e0544b25'},
                                                                                         {'member_fqdn': 'nsx02a.cpod-go.az-fkd.cloud-garage.net',
                                                                                          'member_ip': '172.17.23.12',
                                                                                          'member_status': 'UP',
                                                                                          'member_uuid': 'db1bb097-8ffd-49cc-9280-0dc46f854cd7'},
                                                                                         {'member_fqdn': 'nsx02b.cpod-go.az-fkd.cloud-garage.net',
                                                                                          'member_ip': '172.17.23.13',
                                                                                          'member_status': 'UP',
                                                                                          'member_uuid': '137f0642-612b-b4d6-a86f-5a3fff706ede'},
                                                                                         {'member_fqdn': 'nsx02c.cpod-go.az-fkd.cloud-garage.net',
                                                                                          'member_ip': '172.17.23.14',
                                                                                          'member_status': 'UP',
                                                                                          'member_uuid': 'b1740642-8e0f-4404-a8f5-64cd3811ece6'}]},
                                    '1b944a99-5d3f-3357-b015-fd1ae363072e': {'group_status': 'STABLE',
                                                                             'group_type': 'DATASTORE',
                                                                             'members': [{'member_fqdn': 'nsx-t-a.cpod-go.az-fkd.cloud-garage.net',
                                                                                          'member_ip': '172.17.23.123',
                                                                                          'member_status': 'UNKNOWN',
                                                                                          'member_uuid': '4c1f0642-9739-7919-c5b7-ea9b971d9eb3'},
                                                                                         {'member_fqdn': 'nsx-t-b.cpod-go.az-fkd.cloud-garage.net',
                                                                                          'member_ip': '172.17.23.124',
                                                                                          'member_status': 'UP',
                                                                                          'member_uuid': 'b0fb0642-03b2-91bd-ac6c-4644fe2b8fa3'},
                                                                                         {'member_fqdn': 'nsx-t-c.cpod-go.az-fkd.cloud-garage.net',
                                                                                          'member_ip': '172.17.23.125',
                                                                                          'member_status': 'UP',
                                                                                          'member_uuid': '9dd40642-7e06-7918-dd54-a828e0544b25'},
                                                                                         {'member_fqdn': 'nsx02a.cpod-go.az-fkd.cloud-garage.net',
                                                                                          'member_ip': '172.17.23.12',
                                                                                          'member_status': 'UP',
                                                                                          'member_uuid': 'db1bb097-8ffd-49cc-9280-0dc46f854cd7'},
                                                                                         {'member_fqdn': 'nsx02b.cpod-go.az-fkd.cloud-garage.net',
                                                                                          'member_ip': '172.17.23.13',
                                                                                          'member_status': 'UP',
                                                                                          'member_uuid': '137f0642-612b-b4d6-a86f-5a3fff706ede'},
                                                                                         {'member_fqdn': 'nsx02c.cpod-go.az-fkd.cloud-garage.net',
                                                                                          'member_ip': '172.17.23.14',
                                                                                          'member_status': 'UP',
                                                                                          'member_uuid': 'b1740642-8e0f-4404-a8f5-64cd3811ece6'}]},
                                    '1f2dfa56-7dcf-3583-bedd-f7aec167fec7': {'group_status': 'STABLE',
                                                                             'group_type': 'MANAGER',
                                                                             'members': [{'member_fqdn': 'nsx-t-a.cpod-go.az-fkd.cloud-garage.net',
                                                                                          'member_ip': '172.17.23.123',
                                                                                          'member_status': 'UP',
                                                                                          'member_uuid': '4c1f0642-9739-7919-c5b7-ea9b971d9eb3'},
                                                                                         {'member_fqdn': 'nsx-t-b.cpod-go.az-fkd.cloud-garage.net',
                                                                                          'member_ip': '172.17.23.124',
                                                                                          'member_status': 'UP',
                                                                                          'member_uuid': 'b0fb0642-03b2-91bd-ac6c-4644fe2b8fa3'},
                                                                                         {'member_fqdn': 'nsx-t-c.cpod-go.az-fkd.cloud-garage.net',
                                                                                          'member_ip': '172.17.23.125',
                                                                                          'member_status': 'UP',
                                                                                          'member_uuid': '9dd40642-7e06-7918-dd54-a828e0544b25'},
                                                                                         {'member_fqdn': 'nsx02a.cpod-go.az-fkd.cloud-garage.net',
                                                                                          'member_ip': '172.17.23.12',
                                                                                          'member_status': 'UP',
                                                                                          'member_uuid': 'db1bb097-8ffd-49cc-9280-0dc46f854cd7'},
                                                                                         {'member_fqdn': 'nsx02b.cpod-go.az-fkd.cloud-garage.net',
                                                                                          'member_ip': '172.17.23.13',
                                                                                          'member_status': 'UP',
                                                                                          'member_uuid': '137f0642-612b-b4d6-a86f-5a3fff706ede'},
                                                                                         {'member_fqdn': 'nsx02c.cpod-go.az-fkd.cloud-garage.net',
                                                                                          'member_ip': '172.17.23.14',
                                                                                          'member_status': 'UP',
                                                                                          'member_uuid': 'b1740642-8e0f-4404-a8f5-64cd3811ece6'}]},
                                    '4581dcab-17ff-3256-944c-5083c3defbed': {'group_status': 'DEGRADED',
                                                                             'group_type': 'CONTROLLER',
                                                                             'members': [{'member_fqdn': 'nsx-t-a.cpod-go.az-fkd.cloud-garage.net',
                                                                                          'member_ip': '172.17.23.123',
                                                                                          'member_status': 'DOWN',
                                                                                          'member_uuid': 'eced1373-4c58-444f-8571-39691c114610'},
                                                                                         {'member_fqdn': 'nsx-t-b.cpod-go.az-fkd.cloud-garage.net',
                                                                                          'member_ip': '172.17.23.124',
                                                                                          'member_status': 'UP',
                                                                                          'member_uuid': '2f2133fb-df6e-4ea3-bce4-14bfd6a3f53b'},
                                                                                         {'member_fqdn': 'nsx-t-c.cpod-go.az-fkd.cloud-garage.net',
                                                                                          'member_ip': '172.17.23.125',
                                                                                          'member_status': 'UP',
                                                                                          'member_uuid': 'bf06e1f7-92bc-45b1-913b-d722dec6f5c3'},
                                                                                         {'member_fqdn': 'nsx02a.cpod-go.az-fkd.cloud-garage.net',
                                                                                          'member_ip': '172.17.23.12',
                                                                                          'member_status': 'UP',
                                                                                          'member_uuid': 'ef4f2074-9d2e-4b07-9c14-14d66af1dcce'},
                                                                                         {'member_fqdn': 'nsx02b.cpod-go.az-fkd.cloud-garage.net',
                                                                                          'member_ip': '172.17.23.13',
                                                                                          'member_status': 'UP',
                                                                                          'member_uuid': 'dba1910b-f4c3-4939-a801-80c48e8b615f'},
                                                                                         {'member_fqdn': 'nsx02c.cpod-go.az-fkd.cloud-garage.net',
                                                                                          'member_ip': '172.17.23.14',
                                                                                          'member_status': 'UP',
                                                                                          'member_uuid': '94825b8f-a03d-4bfa-baa3-15d3b4fd3774'}]},
                                    '7bba5b83-a619-3412-859f-897b6a1f5d4d': {'group_status': 'STABLE',
                                                                             'group_type': 'IDPS_REPORTING',
                                                                             'members': [{'member_fqdn': 'nsx-t-a.cpod-go.az-fkd.cloud-garage.net',
                                                                                          'member_ip': '172.17.23.123',
                                                                                          'member_status': 'UP',
                                                                                          'member_uuid': '4c1f0642-9739-7919-c5b7-ea9b971d9eb3'},
                                                                                         {'member_fqdn': 'nsx-t-b.cpod-go.az-fkd.cloud-garage.net',
                                                                                          'member_ip': '172.17.23.124',
                                                                                          'member_status': 'UP',
                                                                                          'member_uuid': 'b0fb0642-03b2-91bd-ac6c-4644fe2b8fa3'},
                                                                                         {'member_fqdn': 'nsx-t-c.cpod-go.az-fkd.cloud-garage.net',
                                                                                          'member_ip': '172.17.23.125',
                                                                                          'member_status': 'UP',
                                                                                          'member_uuid': '9dd40642-7e06-7918-dd54-a828e0544b25'},
                                                                                         {'member_fqdn': 'nsx02a.cpod-go.az-fkd.cloud-garage.net',
                                                                                          'member_ip': '172.17.23.12',
                                                                                          'member_status': 'UP',
                                                                                          'member_uuid': 'db1bb097-8ffd-49cc-9280-0dc46f854cd7'},
                                                                                         {'member_fqdn': 'nsx02b.cpod-go.az-fkd.cloud-garage.net',
                                                                                          'member_ip': '172.17.23.13',
                                                                                          'member_status': 'UP',
                                                                                          'member_uuid': '137f0642-612b-b4d6-a86f-5a3fff706ede'},
                                                                                         {'member_fqdn': 'nsx02c.cpod-go.az-fkd.cloud-garage.net',
                                                                                          'member_ip': '172.17.23.14',
                                                                                          'member_status': 'UP',
                                                                                          'member_uuid': 'b1740642-8e0f-4404-a8f5-64cd3811ece6'}]},
                                    '89948c7f-4890-3f5f-b185-24b4fc3f3611': {'group_status': 'STABLE',
                                                                             'group_type': 'MONITORING',
                                                                             'members': [{'member_fqdn': 'nsx-t-a.cpod-go.az-fkd.cloud-garage.net',
                                                                                          'member_ip': '172.17.23.123',
                                                                                          'member_status': 'UP',
                                                                                          'member_uuid': '4c1f0642-9739-7919-c5b7-ea9b971d9eb3'},
                                                                                         {'member_fqdn': 'nsx-t-b.cpod-go.az-fkd.cloud-garage.net',
                                                                                          'member_ip': '172.17.23.124',
                                                                                          'member_status': 'UP',
                                                                                          'member_uuid': 'b0fb0642-03b2-91bd-ac6c-4644fe2b8fa3'},
                                                                                         {'member_fqdn': 'nsx-t-c.cpod-go.az-fkd.cloud-garage.net',
                                                                                          'member_ip': '172.17.23.125',
                                                                                          'member_status': 'UP',
                                                                                          'member_uuid': '9dd40642-7e06-7918-dd54-a828e0544b25'},
                                                                                         {'member_fqdn': 'nsx02a.cpod-go.az-fkd.cloud-garage.net',
                                                                                          'member_ip': '172.17.23.12',
                                                                                          'member_status': 'UP',
                                                                                          'member_uuid': 'db1bb097-8ffd-49cc-9280-0dc46f854cd7'},
                                                                                         {'member_fqdn': 'nsx02b.cpod-go.az-fkd.cloud-garage.net',
                                                                                          'member_ip': '172.17.23.13',
                                                                                          'member_status': 'UP',
                                                                                          'member_uuid': '137f0642-612b-b4d6-a86f-5a3fff706ede'},
                                                                                         {'member_fqdn': 'nsx02c.cpod-go.az-fkd.cloud-garage.net',
                                                                                          'member_ip': '172.17.23.14',
                                                                                          'member_status': 'UP',
                                                                                          'member_uuid': 'b1740642-8e0f-4404-a8f5-64cd3811ece6'}]},
                                    '8a5da52e-d126-347d-b59e-70c05721a8aa': {'group_status': 'STABLE',
                                                                             'group_type': 'HTTPS',
                                                                             'members': [{'member_fqdn': 'nsx-t-a.cpod-go.az-fkd.cloud-garage.net',
                                                                                          'member_ip': '172.17.23.123',
                                                                                          'member_status': 'UP',
                                                                                          'member_uuid': '4c1f0642-9739-7919-c5b7-ea9b971d9eb3'},
                                                                                         {'member_fqdn': 'nsx-t-b.cpod-go.az-fkd.cloud-garage.net',
                                                                                          'member_ip': '172.17.23.124',
                                                                                          'member_status': 'UP',
                                                                                          'member_uuid': 'b0fb0642-03b2-91bd-ac6c-4644fe2b8fa3'},
                                                                                         {'member_fqdn': 'nsx-t-c.cpod-go.az-fkd.cloud-garage.net',
                                                                                          'member_ip': '172.17.23.125',
                                                                                          'member_status': 'UP',
                                                                                          'member_uuid': '9dd40642-7e06-7918-dd54-a828e0544b25'},
                                                                                         {'member_fqdn': 'nsx02a.cpod-go.az-fkd.cloud-garage.net',
                                                                                          'member_ip': '172.17.23.12',
                                                                                          'member_status': 'UP',
                                                                                          'member_uuid': 'db1bb097-8ffd-49cc-9280-0dc46f854cd7'},
                                                                                         {'member_fqdn': 'nsx02b.cpod-go.az-fkd.cloud-garage.net',
                                                                                          'member_ip': '172.17.23.13',
                                                                                          'member_status': 'UP',
                                                                                          'member_uuid': '137f0642-612b-b4d6-a86f-5a3fff706ede'},
                                                                                         {'member_fqdn': 'nsx02c.cpod-go.az-fkd.cloud-garage.net',
                                                                                          'member_ip': '172.17.23.14',
                                                                                          'member_status': 'UP',
                                                                                          'member_uuid': 'b1740642-8e0f-4404-a8f5-64cd3811ece6'}]},
                                    '9a9882a8-3a2b-3d07-a752-790b8828fb6b': {'group_status': 'STABLE',
                                                                             'group_type': 'CLUSTER_BOOT_MANAGER',
                                                                             'members': [{'member_fqdn': 'nsx-t-a.cpod-go.az-fkd.cloud-garage.net',
                                                                                          'member_ip': '172.17.23.123',
                                                                                          'member_status': 'UP',
                                                                                          'member_uuid': '4c1f0642-9739-7919-c5b7-ea9b971d9eb3'},
                                                                                         {'member_fqdn': 'nsx-t-b.cpod-go.az-fkd.cloud-garage.net',
                                                                                          'member_ip': '172.17.23.124',
                                                                                          'member_status': 'UP',
                                                                                          'member_uuid': 'b0fb0642-03b2-91bd-ac6c-4644fe2b8fa3'},
                                                                                         {'member_fqdn': 'nsx-t-c.cpod-go.az-fkd.cloud-garage.net',
                                                                                          'member_ip': '172.17.23.125',
                                                                                          'member_status': 'UP',
                                                                                          'member_uuid': '9dd40642-7e06-7918-dd54-a828e0544b25'},
                                                                                         {'member_fqdn': 'nsx02a.cpod-go.az-fkd.cloud-garage.net',
                                                                                          'member_ip': '172.17.23.12',
                                                                                          'member_status': 'UP',
                                                                                          'member_uuid': 'db1bb097-8ffd-49cc-9280-0dc46f854cd7'},
                                                                                         {'member_fqdn': 'nsx02b.cpod-go.az-fkd.cloud-garage.net',
                                                                                          'member_ip': '172.17.23.13',
                                                                                          'member_status': 'UP',
                                                                                          'member_uuid': '137f0642-612b-b4d6-a86f-5a3fff706ede'},
                                                                                         {'member_fqdn': 'nsx02c.cpod-go.az-fkd.cloud-garage.net',
                                                                                          'member_ip': '172.17.23.14',
                                                                                          'member_status': 'UP',
                                                                                          'member_uuid': 'b1740642-8e0f-4404-a8f5-64cd3811ece6'}]},
                                    'c582dec9-43ff-3b74-baa0-691df291cea6': {'group_status': 'STABLE',
                                                                             'group_type': 'ASYNC_REPLICATOR',
                                                                             'members': [{'member_fqdn': 'nsx-t-a.cpod-go.az-fkd.cloud-garage.net',
                                                                                          'member_ip': '172.17.23.123',
                                                                                          'member_status': 'UP',
                                                                                          'member_uuid': '4c1f0642-9739-7919-c5b7-ea9b971d9eb3'},
                                                                                         {'member_fqdn': 'nsx-t-b.cpod-go.az-fkd.cloud-garage.net',
                                                                                          'member_ip': '172.17.23.124',
                                                                                          'member_status': 'UP',
                                                                                          'member_uuid': 'b0fb0642-03b2-91bd-ac6c-4644fe2b8fa3'},
                                                                                         {'member_fqdn': 'nsx-t-c.cpod-go.az-fkd.cloud-garage.net',
                                                                                          'member_ip': '172.17.23.125',
                                                                                          'member_status': 'UP',
                                                                                          'member_uuid': '9dd40642-7e06-7918-dd54-a828e0544b25'},
                                                                                         {'member_fqdn': 'nsx02a.cpod-go.az-fkd.cloud-garage.net',
                                                                                          'member_ip': '172.17.23.12',
                                                                                          'member_status': 'UP',
                                                                                          'member_uuid': 'db1bb097-8ffd-49cc-9280-0dc46f854cd7'},
                                                                                         {'member_fqdn': 'nsx02b.cpod-go.az-fkd.cloud-garage.net',
                                                                                          'member_ip': '172.17.23.13',
                                                                                          'member_status': 'UP',
                                                                                          'member_uuid': '137f0642-612b-b4d6-a86f-5a3fff706ede'},
                                                                                         {'member_fqdn': 'nsx02c.cpod-go.az-fkd.cloud-garage.net',
                                                                                          'member_ip': '172.17.23.14',
                                                                                          'member_status': 'UP',
                                                                                          'member_uuid': 'b1740642-8e0f-4404-a8f5-64cd3811ece6'}]},
                                    'f4af8b57-8957-3c00-8ce9-105b25609bd6': {'group_status': 'STABLE',
                                                                             'group_type': 'POLICY',
                                                                             'members': [{'member_fqdn': 'nsx-t-a.cpod-go.az-fkd.cloud-garage.net',
                                                                                          'member_ip': '172.17.23.123',
                                                                                          'member_status': 'UP',
                                                                                          'member_uuid': '4c1f0642-9739-7919-c5b7-ea9b971d9eb3'},
                                                                                         {'member_fqdn': 'nsx-t-b.cpod-go.az-fkd.cloud-garage.net',
                                                                                          'member_ip': '172.17.23.124',
                                                                                          'member_status': 'UP',
                                                                                          'member_uuid': 'b0fb0642-03b2-91bd-ac6c-4644fe2b8fa3'},
                                                                                         {'member_fqdn': 'nsx-t-c.cpod-go.az-fkd.cloud-garage.net',
                                                                                          'member_ip': '172.17.23.125',
                                                                                          'member_status': 'UP',
                                                                                          'member_uuid': '9dd40642-7e06-7918-dd54-a828e0544b25'},
                                                                                         {'member_fqdn': 'nsx02a.cpod-go.az-fkd.cloud-garage.net',
                                                                                          'member_ip': '172.17.23.12',
                                                                                          'member_status': 'UP',
                                                                                          'member_uuid': 'db1bb097-8ffd-49cc-9280-0dc46f854cd7'},
                                                                                         {'member_fqdn': 'nsx02b.cpod-go.az-fkd.cloud-garage.net',
                                                                                          'member_ip': '172.17.23.13',
                                                                                          'member_status': 'UP',
                                                                                          'member_uuid': '137f0642-612b-b4d6-a86f-5a3fff706ede'},
                                                                                         {'member_fqdn': 'nsx02c.cpod-go.az-fkd.cloud-garage.net',
                                                                                          'member_ip': '172.17.23.14',
                                                                                          'member_status': 'UP',
                                                                                          'member_uuid': 'b1740642-8e0f-4404-a8f5-64cd3811ece6'}]}},
                         'members': {('172.17.23.12',
                                      'nsx02a.cpod-go.az-fkd.cloud-garage.net'),
                                     ('172.17.23.123',
                                      'nsx-t-a.cpod-go.az-fkd.cloud-garage.net'),
                                     ('172.17.23.124',
                                      'nsx-t-b.cpod-go.az-fkd.cloud-garage.net'),
                                     ('172.17.23.125',
                                      'nsx-t-c.cpod-go.az-fkd.cloud-garage.net'),
                                     ('172.17.23.13',
                                      'nsx02b.cpod-go.az-fkd.cloud-garage.net'),
                                     ('172.17.23.14',
                                      'nsx02c.cpod-go.az-fkd.cloud-garage.net')},
                         'vip_node_uuid': '137f0642-612b-b4d6-a86f-5a3fff706ede'},
 'control_plane_status': 'DEGRADED',
 'management_offline': None,
 'management_online': [{'mgmt_cluster_listen_ip_address': '172.17.23.13',
 'uuid': '137f0642-612b-b4d6-a86f-5a3fff706ede'},
                       {'mgmt_cluster_listen_ip_address': '172.17.23.124',
 'uuid': 'b0fb0642-03b2-91bd-ac6c-4644fe2b8fa3'},
                       {'mgmt_cluster_listen_ip_address': '172.17.23.123',
 'uuid': '4c1f0642-9739-7919-c5b7-ea9b971d9eb3'},
                       {'mgmt_cluster_listen_ip_address': '172.17.23.14',
 'uuid': 'b1740642-8e0f-4404-a8f5-64cd3811ece6'},
                       {'mgmt_cluster_listen_ip_address': '172.17.23.12',
 'uuid': 'db1bb097-8ffd-49cc-9280-0dc46f854cd7'},
                       {'mgmt_cluster_listen_ip_address': '172.17.23.125',
 'uuid': '9dd40642-7e06-7918-dd54-a828e0544b25'}],
 'management_plane_status': 'STABLE',
 'overall_status': 'DEGRADED'}