# coding: utf-8

"""
    NSX-T Manager API

    VMware NSX-T Manager REST API  # noqa: E501

    OpenAPI spec version: 3.1.0.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class InstructionInfo(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'fields': 'list[str]',
        'id': 'str',
        'actions': 'list[str]',
        'name': 'str'
    }

    attribute_map = {
        'fields': 'fields',
        'id': 'id',
        'actions': 'actions',
        'name': 'name'
    }

    def __init__(self, fields=None, id=None, actions=None, name=None):  # noqa: E501
        """InstructionInfo - a model defined in Swagger"""  # noqa: E501
        self._fields = None
        self._id = None
        self._actions = None
        self._name = None
        self.discriminator = None
        if fields is not None:
            self.fields = fields
        if id is not None:
            self.id = id
        if actions is not None:
            self.actions = actions
        if name is not None:
            self.name = name

    @property
    def fields(self):
        """Gets the fields of this InstructionInfo.  # noqa: E501

        A list of fields that are displayable to users in a table  # noqa: E501

        :return: The fields of this InstructionInfo.  # noqa: E501
        :rtype: list[str]
        """
        return self._fields

    @fields.setter
    def fields(self, fields):
        """Sets the fields of this InstructionInfo.

        A list of fields that are displayable to users in a table  # noqa: E501

        :param fields: The fields of this InstructionInfo.  # noqa: E501
        :type: list[str]
        """

        self._fields = fields

    @property
    def id(self):
        """Gets the id of this InstructionInfo.  # noqa: E501

        UUID of the instruction  # noqa: E501

        :return: The id of this InstructionInfo.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this InstructionInfo.

        UUID of the instruction  # noqa: E501

        :param id: The id of this InstructionInfo.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def actions(self):
        """Gets the actions of this InstructionInfo.  # noqa: E501

        A list of actions that are to be applied to resources  # noqa: E501

        :return: The actions of this InstructionInfo.  # noqa: E501
        :rtype: list[str]
        """
        return self._actions

    @actions.setter
    def actions(self, actions):
        """Sets the actions of this InstructionInfo.

        A list of actions that are to be applied to resources  # noqa: E501

        :param actions: The actions of this InstructionInfo.  # noqa: E501
        :type: list[str]
        """

        self._actions = actions

    @property
    def name(self):
        """Gets the name of this InstructionInfo.  # noqa: E501

        Instruction name  # noqa: E501

        :return: The name of this InstructionInfo.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this InstructionInfo.

        Instruction name  # noqa: E501

        :param name: The name of this InstructionInfo.  # noqa: E501
        :type: str
        """

        self._name = name

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(InstructionInfo, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, InstructionInfo):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
