# coding: utf-8

"""
    NSX-T Manager API

    VMware NSX-T Manager REST API  # noqa: E501

    OpenAPI spec version: 3.1.0.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class L2VPNSessionRemoteMacs(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'remote_mac_addresses': 'list[L2VPNSessionRemoteMacsForLS]',
        'display_name': 'str',
        'session_id': 'str'
    }

    attribute_map = {
        'remote_mac_addresses': 'remote_mac_addresses',
        'display_name': 'display_name',
        'session_id': 'session_id'
    }

    def __init__(self, remote_mac_addresses=None, display_name=None, session_id=None):  # noqa: E501
        """L2VPNSessionRemoteMacs - a model defined in Swagger"""  # noqa: E501
        self._remote_mac_addresses = None
        self._display_name = None
        self._session_id = None
        self.discriminator = None
        if remote_mac_addresses is not None:
            self.remote_mac_addresses = remote_mac_addresses
        if display_name is not None:
            self.display_name = display_name
        if session_id is not None:
            self.session_id = session_id

    @property
    def remote_mac_addresses(self):
        """Gets the remote_mac_addresses of this L2VPNSessionRemoteMacs.  # noqa: E501

        List MAC addresses for all logical switch for a particular L2VPN session.  # noqa: E501

        :return: The remote_mac_addresses of this L2VPNSessionRemoteMacs.  # noqa: E501
        :rtype: list[L2VPNSessionRemoteMacsForLS]
        """
        return self._remote_mac_addresses

    @remote_mac_addresses.setter
    def remote_mac_addresses(self, remote_mac_addresses):
        """Sets the remote_mac_addresses of this L2VPNSessionRemoteMacs.

        List MAC addresses for all logical switch for a particular L2VPN session.  # noqa: E501

        :param remote_mac_addresses: The remote_mac_addresses of this L2VPNSessionRemoteMacs.  # noqa: E501
        :type: list[L2VPNSessionRemoteMacsForLS]
        """

        self._remote_mac_addresses = remote_mac_addresses

    @property
    def display_name(self):
        """Gets the display_name of this L2VPNSessionRemoteMacs.  # noqa: E501

        L2VPN display name.  # noqa: E501

        :return: The display_name of this L2VPNSessionRemoteMacs.  # noqa: E501
        :rtype: str
        """
        return self._display_name

    @display_name.setter
    def display_name(self, display_name):
        """Sets the display_name of this L2VPNSessionRemoteMacs.

        L2VPN display name.  # noqa: E501

        :param display_name: The display_name of this L2VPNSessionRemoteMacs.  # noqa: E501
        :type: str
        """

        self._display_name = display_name

    @property
    def session_id(self):
        """Gets the session_id of this L2VPNSessionRemoteMacs.  # noqa: E501

        L2VPN session identifier.  # noqa: E501

        :return: The session_id of this L2VPNSessionRemoteMacs.  # noqa: E501
        :rtype: str
        """
        return self._session_id

    @session_id.setter
    def session_id(self, session_id):
        """Sets the session_id of this L2VPNSessionRemoteMacs.

        L2VPN session identifier.  # noqa: E501

        :param session_id: The session_id of this L2VPNSessionRemoteMacs.  # noqa: E501
        :type: str
        """

        self._session_id = session_id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(L2VPNSessionRemoteMacs, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, L2VPNSessionRemoteMacs):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
