# coding: utf-8

"""
    NSX-T Manager API

    VMware NSX-T Manager REST API  # noqa: E501

    OpenAPI spec version: 3.1.0.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class LbRuleCondition(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'inverse': 'bool',
        'type': 'str'
    }

    attribute_map = {
        'inverse': 'inverse',
        'type': 'type'
    }

    discriminator_value_class_map = {
          'LbHttpRequestUriArgumentsCondition': 'LbHttpRequestUriArgumentsCondition',
'LbHttpRequestHeaderCondition': 'LbHttpRequestHeaderCondition',
'LbSslSniCondition': 'LbSslSniCondition',
'LbHttpRequestMethodCondition': 'LbHttpRequestMethodCondition',
'LbIpHeaderCondition': 'LbIpHeaderCondition',
'LbHttpRequestBodyCondition': 'LbHttpRequestBodyCondition',
'LbTcpHeaderCondition': 'LbTcpHeaderCondition',
'LbHttpRequestVersionCondition': 'LbHttpRequestVersionCondition',
'LbHttpResponseHeaderCondition': 'LbHttpResponseHeaderCondition',
'LbHttpRequestCookieCondition': 'LbHttpRequestCookieCondition',
'LbHttpRequestUriCondition': 'LbHttpRequestUriCondition',
'LbVariableCondition': 'LbVariableCondition',
'LbHttpSslCondition': 'LbHttpSslCondition'    }

    def __init__(self, inverse=False, type=None):  # noqa: E501
        """LbRuleCondition - a model defined in Swagger"""  # noqa: E501
        self._inverse = None
        self._type = None
        self.discriminator = 'type'
        if inverse is not None:
            self.inverse = inverse
        self.type = type

    @property
    def inverse(self):
        """Gets the inverse of this LbRuleCondition.  # noqa: E501

        A flag to indicate whether reverse the match result of this condition  # noqa: E501

        :return: The inverse of this LbRuleCondition.  # noqa: E501
        :rtype: bool
        """
        return self._inverse

    @inverse.setter
    def inverse(self, inverse):
        """Sets the inverse of this LbRuleCondition.

        A flag to indicate whether reverse the match result of this condition  # noqa: E501

        :param inverse: The inverse of this LbRuleCondition.  # noqa: E501
        :type: bool
        """

        self._inverse = inverse

    @property
    def type(self):
        """Gets the type of this LbRuleCondition.  # noqa: E501

        Type of load balancer rule condition  # noqa: E501

        :return: The type of this LbRuleCondition.  # noqa: E501
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this LbRuleCondition.

        Type of load balancer rule condition  # noqa: E501

        :param type: The type of this LbRuleCondition.  # noqa: E501
        :type: str
        """
        if type is None:
            raise ValueError("Invalid value for `type`, must not be `None`")  # noqa: E501
        allowed_values = ["LbHttpRequestMethodCondition", "LbHttpRequestUriCondition", "LbHttpRequestUriArgumentsCondition", "LbHttpRequestVersionCondition", "LbHttpRequestHeaderCondition", "LbHttpRequestCookieCondition", "LbHttpRequestBodyCondition", "LbHttpResponseHeaderCondition", "LbTcpHeaderCondition", "LbIpHeaderCondition", "LbVariableCondition", "LbHttpSslCondition", "LbSslSniCondition"]  # noqa: E501
        if type not in allowed_values:
            raise ValueError(
                "Invalid value for `type` ({0}), must be one of {1}"  # noqa: E501
                .format(type, allowed_values)
            )

        self._type = type

    def get_real_child_model(self, data):
        """Returns the real base class specified by the discriminator"""
        discriminator_value = data[self.discriminator].lower()
        return self.discriminator_value_class_map.get(discriminator_value)

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(LbRuleCondition, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, LbRuleCondition):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
