# coding: utf-8

"""
    NSX-T Manager API

    VMware NSX-T Manager REST API  # noqa: E501

    OpenAPI spec version: 3.1.0.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six
from swagger_client.models.managed_resource import ManagedResource  # noqa: F401,E501

class MigrationUnitGroupAggregateInfo(ManagedResource):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'status': 'str',
        'failed_count': 'int',
        'group': 'MigrationUnitGroup',
        'percent_complete': 'float'
    }
    if hasattr(ManagedResource, "swagger_types"):
        swagger_types.update(ManagedResource.swagger_types)

    attribute_map = {
        'status': 'status',
        'failed_count': 'failed_count',
        'group': 'group',
        'percent_complete': 'percent_complete'
    }
    if hasattr(ManagedResource, "attribute_map"):
        attribute_map.update(ManagedResource.attribute_map)

    def __init__(self, status=None, failed_count=None, group=None, percent_complete=None, *args, **kwargs):  # noqa: E501
        """MigrationUnitGroupAggregateInfo - a model defined in Swagger"""  # noqa: E501
        self._status = None
        self._failed_count = None
        self._group = None
        self._percent_complete = None
        self.discriminator = None
        if status is not None:
            self.status = status
        if failed_count is not None:
            self.failed_count = failed_count
        self.group = group
        if percent_complete is not None:
            self.percent_complete = percent_complete
        ManagedResource.__init__(self, *args, **kwargs)

    @property
    def status(self):
        """Gets the status of this MigrationUnitGroupAggregateInfo.  # noqa: E501

        Migration status of migration unit group  # noqa: E501

        :return: The status of this MigrationUnitGroupAggregateInfo.  # noqa: E501
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this MigrationUnitGroupAggregateInfo.

        Migration status of migration unit group  # noqa: E501

        :param status: The status of this MigrationUnitGroupAggregateInfo.  # noqa: E501
        :type: str
        """
        allowed_values = ["SUCCESS", "FAILED", "IN_PROGRESS", "NOT_STARTED", "PAUSED"]  # noqa: E501
        if status not in allowed_values:
            raise ValueError(
                "Invalid value for `status` ({0}), must be one of {1}"  # noqa: E501
                .format(status, allowed_values)
            )

        self._status = status

    @property
    def failed_count(self):
        """Gets the failed_count of this MigrationUnitGroupAggregateInfo.  # noqa: E501

        Number of nodes in the migration unit group that failed migration  # noqa: E501

        :return: The failed_count of this MigrationUnitGroupAggregateInfo.  # noqa: E501
        :rtype: int
        """
        return self._failed_count

    @failed_count.setter
    def failed_count(self, failed_count):
        """Sets the failed_count of this MigrationUnitGroupAggregateInfo.

        Number of nodes in the migration unit group that failed migration  # noqa: E501

        :param failed_count: The failed_count of this MigrationUnitGroupAggregateInfo.  # noqa: E501
        :type: int
        """

        self._failed_count = failed_count

    @property
    def group(self):
        """Gets the group of this MigrationUnitGroupAggregateInfo.  # noqa: E501


        :return: The group of this MigrationUnitGroupAggregateInfo.  # noqa: E501
        :rtype: MigrationUnitGroup
        """
        return self._group

    @group.setter
    def group(self, group):
        """Sets the group of this MigrationUnitGroupAggregateInfo.


        :param group: The group of this MigrationUnitGroupAggregateInfo.  # noqa: E501
        :type: MigrationUnitGroup
        """
        if group is None:
            raise ValueError("Invalid value for `group`, must not be `None`")  # noqa: E501

        self._group = group

    @property
    def percent_complete(self):
        """Gets the percent_complete of this MigrationUnitGroupAggregateInfo.  # noqa: E501

        Indicator of migration progress in percentage  # noqa: E501

        :return: The percent_complete of this MigrationUnitGroupAggregateInfo.  # noqa: E501
        :rtype: float
        """
        return self._percent_complete

    @percent_complete.setter
    def percent_complete(self, percent_complete):
        """Sets the percent_complete of this MigrationUnitGroupAggregateInfo.

        Indicator of migration progress in percentage  # noqa: E501

        :param percent_complete: The percent_complete of this MigrationUnitGroupAggregateInfo.  # noqa: E501
        :type: float
        """

        self._percent_complete = percent_complete

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(MigrationUnitGroupAggregateInfo, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, MigrationUnitGroupAggregateInfo):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
