# coding: utf-8

"""
    NSX-T Manager API

    VMware NSX-T Manager REST API  # noqa: E501

    OpenAPI spec version: 3.1.0.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class PointDefinition(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'y_value': 'str',
        'field': 'str',
        'drilldown_id': 'str',
        'x_value': 'str',
        'navigation': 'str',
        'tooltip': 'list[Tooltip]'
    }

    attribute_map = {
        'y_value': 'y_value',
        'field': 'field',
        'drilldown_id': 'drilldown_id',
        'x_value': 'x_value',
        'navigation': 'navigation',
        'tooltip': 'tooltip'
    }

    def __init__(self, y_value=None, field=None, drilldown_id=None, x_value=None, navigation=None, tooltip=None):  # noqa: E501
        """PointDefinition - a model defined in Swagger"""  # noqa: E501
        self._y_value = None
        self._field = None
        self._drilldown_id = None
        self._x_value = None
        self._navigation = None
        self._tooltip = None
        self.discriminator = None
        self.y_value = y_value
        self.field = field
        if drilldown_id is not None:
            self.drilldown_id = drilldown_id
        self.x_value = x_value
        if navigation is not None:
            self.navigation = navigation
        if tooltip is not None:
            self.tooltip = tooltip

    @property
    def y_value(self):
        """Gets the y_value of this PointDefinition.  # noqa: E501

        Represents the variable for the Y value of points that are plotted on the graph.  # noqa: E501

        :return: The y_value of this PointDefinition.  # noqa: E501
        :rtype: str
        """
        return self._y_value

    @y_value.setter
    def y_value(self, y_value):
        """Sets the y_value of this PointDefinition.

        Represents the variable for the Y value of points that are plotted on the graph.  # noqa: E501

        :param y_value: The y_value of this PointDefinition.  # noqa: E501
        :type: str
        """
        if y_value is None:
            raise ValueError("Invalid value for `y_value`, must not be `None`")  # noqa: E501

        self._y_value = y_value

    @property
    def field(self):
        """Gets the field of this PointDefinition.  # noqa: E501

        An expression that represents the points of the graph  # noqa: E501

        :return: The field of this PointDefinition.  # noqa: E501
        :rtype: str
        """
        return self._field

    @field.setter
    def field(self, field):
        """Sets the field of this PointDefinition.

        An expression that represents the points of the graph  # noqa: E501

        :param field: The field of this PointDefinition.  # noqa: E501
        :type: str
        """
        if field is None:
            raise ValueError("Invalid value for `field`, must not be `None`")  # noqa: E501

        self._field = field

    @property
    def drilldown_id(self):
        """Gets the drilldown_id of this PointDefinition.  # noqa: E501

        Id of drilldown widget, if any. Id should be a valid id of an existing widget. A widget is considered as drilldown widget when it is associated with any other widget and provides more detailed information about any data item from the parent widget.  # noqa: E501

        :return: The drilldown_id of this PointDefinition.  # noqa: E501
        :rtype: str
        """
        return self._drilldown_id

    @drilldown_id.setter
    def drilldown_id(self, drilldown_id):
        """Sets the drilldown_id of this PointDefinition.

        Id of drilldown widget, if any. Id should be a valid id of an existing widget. A widget is considered as drilldown widget when it is associated with any other widget and provides more detailed information about any data item from the parent widget.  # noqa: E501

        :param drilldown_id: The drilldown_id of this PointDefinition.  # noqa: E501
        :type: str
        """

        self._drilldown_id = drilldown_id

    @property
    def x_value(self):
        """Gets the x_value of this PointDefinition.  # noqa: E501

        Represents the variable for the X value of points that are plotted on the graph.  # noqa: E501

        :return: The x_value of this PointDefinition.  # noqa: E501
        :rtype: str
        """
        return self._x_value

    @x_value.setter
    def x_value(self, x_value):
        """Sets the x_value of this PointDefinition.

        Represents the variable for the X value of points that are plotted on the graph.  # noqa: E501

        :param x_value: The x_value of this PointDefinition.  # noqa: E501
        :type: str
        """
        if x_value is None:
            raise ValueError("Invalid value for `x_value`, must not be `None`")  # noqa: E501

        self._x_value = x_value

    @property
    def navigation(self):
        """Gets the navigation of this PointDefinition.  # noqa: E501

        Hyperlink of the specified UI page that provides details.  # noqa: E501

        :return: The navigation of this PointDefinition.  # noqa: E501
        :rtype: str
        """
        return self._navigation

    @navigation.setter
    def navigation(self, navigation):
        """Sets the navigation of this PointDefinition.

        Hyperlink of the specified UI page that provides details.  # noqa: E501

        :param navigation: The navigation of this PointDefinition.  # noqa: E501
        :type: str
        """

        self._navigation = navigation

    @property
    def tooltip(self):
        """Gets the tooltip of this PointDefinition.  # noqa: E501

        Multi-line text to be shown on tooltip while hovering over the point of a graph.  # noqa: E501

        :return: The tooltip of this PointDefinition.  # noqa: E501
        :rtype: list[Tooltip]
        """
        return self._tooltip

    @tooltip.setter
    def tooltip(self, tooltip):
        """Sets the tooltip of this PointDefinition.

        Multi-line text to be shown on tooltip while hovering over the point of a graph.  # noqa: E501

        :param tooltip: The tooltip of this PointDefinition.  # noqa: E501
        :type: list[Tooltip]
        """

        self._tooltip = tooltip

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(PointDefinition, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, PointDefinition):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
