# coding: utf-8

"""
    NSX-T Manager API

    VMware NSX-T Manager REST API  # noqa: E501

    OpenAPI spec version: 3.1.0.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six
from swagger_client.models.managed_resource import ManagedResource  # noqa: F401,E501

class RedistributionConfig(ManagedResource):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'logical_router_id': 'str',
        'bgp_enabled': 'bool'
    }
    if hasattr(ManagedResource, "swagger_types"):
        swagger_types.update(ManagedResource.swagger_types)

    attribute_map = {
        'logical_router_id': 'logical_router_id',
        'bgp_enabled': 'bgp_enabled'
    }
    if hasattr(ManagedResource, "attribute_map"):
        attribute_map.update(ManagedResource.attribute_map)

    def __init__(self, logical_router_id=None, bgp_enabled=False, *args, **kwargs):  # noqa: E501
        """RedistributionConfig - a model defined in Swagger"""  # noqa: E501
        self._logical_router_id = None
        self._bgp_enabled = None
        self.discriminator = None
        if logical_router_id is not None:
            self.logical_router_id = logical_router_id
        if bgp_enabled is not None:
            self.bgp_enabled = bgp_enabled
        ManagedResource.__init__(self, *args, **kwargs)

    @property
    def logical_router_id(self):
        """Gets the logical_router_id of this RedistributionConfig.  # noqa: E501

        Logical router id  # noqa: E501

        :return: The logical_router_id of this RedistributionConfig.  # noqa: E501
        :rtype: str
        """
        return self._logical_router_id

    @logical_router_id.setter
    def logical_router_id(self, logical_router_id):
        """Sets the logical_router_id of this RedistributionConfig.

        Logical router id  # noqa: E501

        :param logical_router_id: The logical_router_id of this RedistributionConfig.  # noqa: E501
        :type: str
        """

        self._logical_router_id = logical_router_id

    @property
    def bgp_enabled(self):
        """Gets the bgp_enabled of this RedistributionConfig.  # noqa: E501

        Flag to enable redistribution for BGP as destination protocol  # noqa: E501

        :return: The bgp_enabled of this RedistributionConfig.  # noqa: E501
        :rtype: bool
        """
        return self._bgp_enabled

    @bgp_enabled.setter
    def bgp_enabled(self, bgp_enabled):
        """Sets the bgp_enabled of this RedistributionConfig.

        Flag to enable redistribution for BGP as destination protocol  # noqa: E501

        :param bgp_enabled: The bgp_enabled of this RedistributionConfig.  # noqa: E501
        :type: bool
        """

        self._bgp_enabled = bgp_enabled

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(RedistributionConfig, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, RedistributionConfig):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
