# coding: utf-8

"""
    NSX-T Manager API

    VMware NSX-T Manager REST API  # noqa: E501

    OpenAPI spec version: 3.1.0.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.classless_static_route import ClasslessStaticRoute  # noqa: E501
from swagger_client.rest import ApiException


class TestClasslessStaticRoute(unittest.TestCase):
    """ClasslessStaticRoute unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testClasslessStaticRoute(self):
        """Test ClasslessStaticRoute"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.classless_static_route.ClasslessStaticRoute()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
