# coding: utf-8

"""
    NSX-T Manager API

    VMware NSX-T Manager REST API  # noqa: E501

    OpenAPI spec version: 3.1.0.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.system_administration_configuration_fabric_nodes_user_management_authentication_policy_api import SystemAdministrationConfigurationFabricNodesUserManagementAuthenticationPolicyApi  # noqa: E501
from swagger_client.rest import ApiException


class TestSystemAdministrationConfigurationFabricNodesUserManagementAuthenticationPolicyApi(unittest.TestCase):
    """SystemAdministrationConfigurationFabricNodesUserManagementAuthenticationPolicyApi unit test stubs"""

    def setUp(self):
        self.api = SystemAdministrationConfigurationFabricNodesUserManagementAuthenticationPolicyApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_read_authentication_policy_properties(self):
        """Test case for read_authentication_policy_properties

        Read node authentication policy configuration  # noqa: E501
        """
        pass

    def test_update_authentication_policy_properties(self):
        """Test case for update_authentication_policy_properties

        Update node authentication policy configuration  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
