# coding: utf-8

"""
    NSX-T Manager API

    VMware NSX-T Manager REST API  # noqa: E501

    OpenAPI spec version: 3.1.0.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.system_administration_lifecycle_management_migration_vmgroup_api import SystemAdministrationLifecycleManagementMigrationVmgroupApi  # noqa: E501
from swagger_client.rest import ApiException


class TestSystemAdministrationLifecycleManagementMigrationVmgroupApi(unittest.TestCase):
    """SystemAdministrationLifecycleManagementMigrationVmgroupApi unit test stubs"""

    def setUp(self):
        self.api = SystemAdministrationLifecycleManagementMigrationVmgroupApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_post_vm_group_migrate_post_migrate(self):
        """Test case for post_vm_group_migrate_post_migrate

        Perform steps required after migrating a VM group.  # noqa: E501
        """
        pass

    def test_pre_vm_group_migrate_pre_migrate(self):
        """Test case for pre_vm_group_migrate_pre_migrate

        Perform steps required before migrating a VM group.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
