# coding: utf-8

"""
    NSX-T Manager API

    VMware NSX-T Manager REST API  # noqa: E501

    OpenAPI spec version: 3.1.0.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.system_administration_configuration_nsx_managers_nodes_services_node_stats_service_api import SystemAdministrationConfigurationNSXManagersNodesServicesNodeStatsServiceApi  # noqa: E501
from swagger_client.rest import ApiException


class TestSystemAdministrationConfigurationNSXManagersNodesServicesNodeStatsServiceApi(unittest.TestCase):
    """SystemAdministrationConfigurationNSXManagersNodesServicesNodeStatsServiceApi unit test stubs"""

    def setUp(self):
        self.api = SystemAdministrationConfigurationNSXManagersNodesServicesNodeStatsServiceApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_node_stats_service_action_restart(self):
        """Test case for create_node_stats_service_action_restart

        Restart, start or stop the NSX node-stats service  # noqa: E501
        """
        pass

    def test_create_node_stats_service_action_start(self):
        """Test case for create_node_stats_service_action_start

        Restart, start or stop the NSX node-stats service  # noqa: E501
        """
        pass

    def test_create_node_stats_service_action_stop(self):
        """Test case for create_node_stats_service_action_stop

        Restart, start or stop the NSX node-stats service  # noqa: E501
        """
        pass

    def test_read_node_stats_service(self):
        """Test case for read_node_stats_service

        Read NSX node-stats service properties  # noqa: E501
        """
        pass

    def test_read_node_stats_service_status(self):
        """Test case for read_node_stats_service_status

        Read NSX node-stats service status  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
