# coding: utf-8

"""
    NSX-T Manager API

    VMware NSX-T Manager REST API  # noqa: E501

    OpenAPI spec version: 3.1.0.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.system_administration_configuration_nsx_managers_clusters_cluster_virtual_ip_api import SystemAdministrationConfigurationNSXManagersClustersClusterVirtualIPApi  # noqa: E501
from swagger_client.rest import ApiException


class TestSystemAdministrationConfigurationNSXManagersClustersClusterVirtualIPApi(unittest.TestCase):
    """SystemAdministrationConfigurationNSXManagersClustersClusterVirtualIPApi unit test stubs"""

    def setUp(self):
        self.api = SystemAdministrationConfigurationNSXManagersClustersClusterVirtualIPApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_clear_cluster_virtual_ip_clear_virtual_ip(self):
        """Test case for clear_cluster_virtual_ip_clear_virtual_ip

        Clear cluster virtual IP address  # noqa: E501
        """
        pass

    def test_get_cluster_virtual_ip(self):
        """Test case for get_cluster_virtual_ip

        Read cluster virtual IP address  # noqa: E501
        """
        pass

    def test_set_cluster_virtual_ip_set_virtual_ip(self):
        """Test case for set_cluster_virtual_ip_set_virtual_ip

        Set cluster virtual IP address  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
