# coding: utf-8

"""
    NSX-T Manager API

    VMware NSX-T Manager REST API  # noqa: E501

    OpenAPI spec version: 3.1.0.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.system_administration_configuration_fabric_pool_management_mac_pools_api import SystemAdministrationConfigurationFabricPoolManagementMACPoolsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestSystemAdministrationConfigurationFabricPoolManagementMACPoolsApi(unittest.TestCase):
    """SystemAdministrationConfigurationFabricPoolManagementMACPoolsApi unit test stubs"""

    def setUp(self):
        self.api = SystemAdministrationConfigurationFabricPoolManagementMACPoolsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_list_mac_pools(self):
        """Test case for list_mac_pools

        List MAC Pools  # noqa: E501
        """
        pass

    def test_read_mac_pool(self):
        """Test case for read_mac_pool

        Read MAC Pool  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
