# coding: utf-8

"""
    NSX-T Manager API

    VMware NSX-T Manager REST API  # noqa: E501

    OpenAPI spec version: 3.1.0.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.lb_pool_status import LbPoolStatus  # noqa: E501
from swagger_client.rest import ApiException


class TestLbPoolStatus(unittest.TestCase):
    """LbPoolStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testLbPoolStatus(self):
        """Test LbPoolStatus"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.lb_pool_status.LbPoolStatus()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
