# coding: utf-8

"""
    NSX-T Manager API

    VMware NSX-T Manager REST API  # noqa: E501

    OpenAPI spec version: 3.1.0.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.lb_snat_auto_map import LbSnatAutoMap  # noqa: E501
from swagger_client.rest import ApiException


class TestLbSnatAutoMap(unittest.TestCase):
    """LbSnatAutoMap unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testLbSnatAutoMap(self):
        """Test LbSnatAutoMap"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.lb_snat_auto_map.LbSnatAutoMap()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
