# coding: utf-8

"""
    NSX-T Manager API

    VMware NSX-T Manager REST API  # noqa: E501

    OpenAPI spec version: 3.1.0.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.service_insertion_rule_list import ServiceInsertionRuleList  # noqa: E501
from swagger_client.rest import ApiException


class TestServiceInsertionRuleList(unittest.TestCase):
    """ServiceInsertionRuleList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testServiceInsertionRuleList(self):
        """Test ServiceInsertionRuleList"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.service_insertion_rule_list.ServiceInsertionRuleList()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
