# coding: utf-8

"""
    NSX-T Manager API

    VMware NSX-T Manager REST API  # noqa: E501

    OpenAPI spec version: 3.1.0.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.management_plane_api_networking_vpn_statistics_ike_sessions_status_api import ManagementPlaneAPINetworkingVPNStatisticsIKESessionsStatusApi  # noqa: E501
from swagger_client.rest import ApiException


class TestManagementPlaneAPINetworkingVPNStatisticsIKESessionsStatusApi(unittest.TestCase):
    """ManagementPlaneAPINetworkingVPNStatisticsIKESessionsStatusApi unit test stubs"""

    def setUp(self):
        self.api = ManagementPlaneAPINetworkingVPNStatisticsIKESessionsStatusApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_ip_sec_vpnike_session_status(self):
        """Test case for get_ip_sec_vpnike_session_status

        Get IPSec VPN IKE session status  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
